version: '3.8'
services:
  gaia:
    # Prevent the container from exiting after initialisation
    command: /bin/sh -c "while sleep 1000; do :; done"

    volumes:
      # Replace placeholder service name
      - .:/workspaces/gaia:cached
